### ISSUE TITLE
Include the answers in the JSON string that is sent to view.py

### ISSUE THREAD

**Issue by ghost** [ndiquattro/classqs#2]
Modify the createquestion JS to send asnwers in the JSON POST

**Comment by ndiquattro** [comment]
Ideally they would come in grouped under one header. Something like:

``` python
{'CorrAns': 'Nick', 'NAns': '2', u'QuesName': 'Good question', 'QuesTxt': "Who's the coolest?", 'FolderName': 'Old Folder1',
'options': {'option1': 'Nick', 'option2': 'Adam'} # or even better
'options':['Nick', 'Adam']
}
```

**Comment by ghost** [comment]
By the "even better" example are you saying you prefer a long array with just the answer txt (just options = [Nick, Adam] and not a key value pair [Option1=Nick, Option2=Adam]? If so wouldn't a key value pair be better so you know which sql column to put the answers in?

I'll keep it key/pair for now and I can pretty easily change it if you want it another way

**Comment by ghost** [comment]
So I think I get what you were saying and the views.py now has: Answers = ['Adam', 'Nick'], with Adam being the clear winner. Let me know if this is good and we can click that fancy close button!
